# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12199cb971a22cd2ea954f7177d5786c4364ddb48bdb3977a024b2cafe9412958d88a2c946fde1732a51d717ebcae2cdb1cd412a9705a9dcf191ef59cf1d7f3c

test:
  secret_key_base: 0692d0bed6a62d415458493cafc74cc756662cd96090a2047e45448127cf1c405132a5729677958c62d1d55c07082e809a9894478324a82aaa5efad4130da0a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
